# Generated by Django 5.2 on 2025-05-04 15:31

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_user_department_user_middle_name_user_phone_number_and_more'),
    ]

    operations = [
        # 1) Очищуємо пусті рядки, замінюючи їх на NULL
        migrations.RunSQL(
            sql=[
                "UPDATE production_user SET department = NULL WHERE department = '';",
                "UPDATE production_user SET position   = NULL WHERE position   = '';"
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 2) Створюємо нові моделі
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),

        # 3) Інші правки полів
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='production.department',
                verbose_name='Відділ'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='production.position',
                verbose_name='Посада'
            ),
        ),
    ]
