# Generated by Django 5.2 on 2025-05-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_user_middle_name_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='production.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
