# Generated by Django 5.2 on 2025-05-13 10:47

from django.db import migrations, models
import datetime
import pytz

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_project_department_project_last_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 5, 13, 10, 47, tzinfo=pytz.UTC)
            ),
            preserve_default=False,
        ),
    ]
