# Generated by Django 5.2 on 2025-05-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_tasknotification_recipient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectComment',
            new_name='Comments',
        ),
    ]
